### ISSUE TITLE
VcfStack class defined in gQTLstats

### ISSUE THREAD

**Issue by vjcitn** [vjcitn/biocMultiAssay#57]
VCF archives are often broken up by chromosome.  VcfStack is an attempt to allow manipulation of such collections through a single object.  Code is in the devel branch of gQTLstats, with man page/example.

**Comment by LiNk-NY** [comment]
@vjcitn 
Hi Vince,
I tried to install your gQTLstats package using R-devel (2015-11-19 r69663) and Bioconductor devel 3.3 but I was unable to install it because the Matrix package isn't working for me (Matrix_1.2-2.tar.gz).

This is the error I'm getting: 
Creating a generic function for ‘update’ from package ‘stats’ in package ‘Matrix’
Error in match.call(definition, call, expand.dots, envir) : 
  unused argument (mode = c("missing", "methods"))
Error : unable to load R code in package ‘Matrix’
ERROR: lazy loading failed for package ‘Matrix’

I'd appreciate if you could help me. Perhaps you've had this error before?

**Comment by mtmorgan** [comment]
tools/rsync-recommended pulls down Matrix_1.2-3.tar.gz

**Comment by LiNk-NY** [comment]
@mtmorgan 
Hi Martin, 
Thank you for your help in this. I built R-devel from source but I wasn't able to resolve the issue. Below are the scripts that I used to build (in a gist). Was it built correctly? 

[Click Here](https://gist.github.com/LiNk-NY/e9ca59b973aca2e16f43)

Regards, 
Marcel

**Comment by mtmorgan** [comment]
'Matrix' is a recommended package

```
> installed.packages()["Matrix", "Priority"]
      Version      Priority 
      "1.2-3" "recommended" 
```

but your build flag is `--without-recommended-packages` so although you've rsync'ed, you're still using an old version (probably from a previous installation, in your user path??)

**Comment by vjcitn** [comment]
There was a time recently when I was certainly running into

Creating a generic function for ‘update’ from package ‘stats’ in package
‘Matrix’
Error in match.call(definition, call, expand.dots, envir) :
unused argument (mode = c("missing", "methods"))
Error : unable to load R code in package ‘Matrix’
ERROR: lazy loading failed for package ‘Matrix’

and this had nothing to do with gQTLstats.  here is my current sessioninfo.
 what is yours,
and what is the error you are encountering -- upon library(Matrix) or only
upon attempt to
install gQTLstats?  please give full details

> sessionInfo()

R Under development (unstable) (2015-11-11 r69621)

Platform: x86_64-apple-darwin13.4.0 (64-bit)

Running under: OS X 10.10.5 (Yosemite)


locale:

[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8


attached base packages:

[1] stats     graphics  grDevices datasets  parallel  utils     tools

[8] methods   base


other attached packages:

 [1] Matrix_1.2-2         doParallel_1.0.10    iterators_1.0.8

 [4] foreach_1.4.3        rmarkdown_0.8.1      knitr_1.11

 [7] weaver_1.37.0        codetools_0.2-14     digest_0.6.8

[10] hwriter_1.3.2        shiny_0.12.2         BiocInstaller_1.21.2


loaded via a namespace (and not attached):

[1] Rcpp_0.12.2     lattice_0.20-33 mime_0.4        grid_3.3.0

[5] R6_2.1.1        xtable_1.8-0    httpuv_1.3.3    htmltools_0.2.6

**Comment by vjcitn** [comment]
On Wed, Nov 25, 2015 at 4:31 PM, Martin Morgan <notifications@github.com>
wrote:

> 'Matrix' is a recommended package
>
> > installed.packages()["Matrix", "Priority"]
>       Version      Priority
>       "1.2-3" "recommended"
>
> but your build flag is --without-recommended-packages so although you've
> rsync'ed, you're still using an old
>

yes, why would you set that?

**Comment by LiNk-NY** [comment]
@mtmorgan @vjcitn 
I wasn't using an old one because it never got installed. I rebuilt R-devel without the `--without-recommended-packages` flag and it started working. Finally got the "gQTLstats" package to install. It was just the Matrix library that was giving me trouble (aside from libRblas.so). 
Thanks all!
