### ISSUE TITLE
changes for entry to inclusion in bioc devel branch

### ISSUE THREAD

**Issue by vjcitn** [vjcitn/biocMultiAssay#65]
Package/class/constructor name = MultiAssayExperiment

elist to Elist

Stage to MultiAssayView

GRangesList wrapped in RaggedRangedAssay

Levi's previous list of methods for Elist-eligible classes is adopted

**Comment by lwaldron** [comment]
Not mentioned in your list Vince, but I think the verb stage() should stay
as-is, and only the resulting class be renamed to MultiAssayView.
>
>

-- 
Levi Waldron
Assistant Professor of Biostatistics
City University of New York School of Public Health, Hunter College
2180 3rd Ave Rm 538
New York NY 10035-4003
phone: 212-396-7747
www.waldronlab.org

**Comment by lwaldron** [comment]
Copying the list of methods from another issue to have it all in the same place:

The key operations we'll need for manipulation are equivalent to rownames/colnames/"["/assay.  `assay()` returns a rxc matrix of the assay data.  If we use these, by my probably incomplete tally we'll need to define the following for base classes:

`RangedSummarizedExperiment`: none
`GRangesList`: rownames, colnames, "[", assay. "[" would only be defined for character arguments before and after comma.
`matrix`: assay
`ExpressionSet`: assay

For the MultiAssayExperiment, the `subset(myMA, method="samples")` seems intuitive, and can call the `Stage()` function first so that the subset function that does the real work always acts on a `Stage` object.
